name: CrashCourse pipeline

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: My name
      run: echo Kyryl Kuchynskyi
      
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configuring Pages
      uses: actions/configure-pages@v3
    
    - name: Build with Jekyll
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./
        destination: ./_site
        
    - name: Upload
      uses: actions/upload-pages-artifact@v2
      
  cd:
    needs: [ci]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deployment
      id: deployment
      uses: actions/deploy-pages@v2
    
